# Site settings
author: David Goldstein
title: Final Project Blogs
header-img: img/home-bg.png
email: dg2996@columbia.edu
copyright_name: David Goldstein
description: > # this means to ignore newlines until "baseurl:"
  Flatiron Data Science Part-Time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dgoldstein24

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
